"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%oeichix$*eb3!69_--%i02#f+tm4-mj00k#(f@*#x^_9y!-20'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['southparker.pythonanywhere.com','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'mysite',
    "myapp.apps.MyappConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 데이터베이스 엔진
        'NAME': 'war_place',                  # 데이터베이스 이름
        'USER': 'root',              # 데이터베이스 사용자
        'PASSWORD': 'ododoc1234',             # 데이터베이스 비밀번호
        'HOST': 'localhost',                  # 데이터베이스 호스트 (일반적으로 'localhost' 또는 '127.0.0.1')
        'PORT': '3306',                       # 데이터베이스 포트
        'OPTIONS': {
            'charset': 'utf8mb4',             # 문자 인코딩 설정 (옵션)
        },
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # 데이터베이스 엔진
#         'NAME': 'southparker$sky_place',                  # 데이터베이스 이름
#         'USER': 'southparker',              # 데이터베이스 사용자
#         'PASSWORD': 'ododoc1234',             # 데이터베이스 비밀번호
#         'HOST': 'southparker.mysql.pythonanywhere-services.com',                  # 데이터베이스 호스트 (일반적으로 'localhost' 또는 '127.0.0.1')
#         'PORT': '3306',                       # 데이터베이스 포트
#         'OPTIONS': {
#             'charset': 'utf8mb4',             # 문자 인코딩 설정 (옵션)
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/southparker/mysite/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/southparker/mysite/static'
STATIC_URL = '/static/'
