# Generated by Django 4.2.4 on 2023-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memid', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
    ]
